name: Publish to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'

    - name: Set execute permission for verify-version-file.sh
      run: chmod +x ./scripts/verify-version-file.sh

    - name: Install dependencies
      run: npm install

    - name: Read version type from file
      id: read_version
      run: echo "VERSION_TYPE=$(cat version-type.txt)" >> $GITHUB_ENV

    - name: Get previous version
      id: get_prev_version
      run: echo "PREV_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

    - name: Bump version and publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        VERSION_TYPE: ${{ env.VERSION_TYPE }}
      run: |
        # Atualiza a versão no package.json e package-lock.json
        NEW_VERSION=$(cat version-type.txt)
        npm version $NEW_VERSION --no-git-tag-version

        # Construa o projeto (se necessário)
        npm run build
        
        # Comita e envia a mudança de versão
        git config --global user.name 'github-actions[bot]'
        git config --global user.email github-actions@github.com
        git add --all
        git commit -m "Bump version from ${{ env.PREV_VERSION }} to $NEW_VERSION" --no-verify
        
        
        npm publish --registry=https://registry.npmjs.org/ --access=public

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.VERSION_TYPE }}
          release_name: Release ${{ env.VERSION_TYPE }}
          body: |
            Release ${{ env.VERSION_TYPE }} - Describe your release here.
            
    - name: Push changes
      run: |
              git tag v$(cat version-type.txt)
              git push origin main --tags