name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check if info.json changed
      id: check_changes
      run: |
          if git diff --name-only HEAD~1 HEAD | grep -q 'info.json'; then
            echo "info.json has changed."
            echo "::set-output name=changed::true"
          else
            echo "info.json has not changed."
            echo "::set-output name=changed::false"
          fi

    - name: Check out repository
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/checkout@v2

    - name: Set up Node.js
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: '14'


    - name: Install dependencies
      if: steps.check_changes.outputs.changed == 'true'
      run: npm install

    - name: Run command and update README
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        OUTPUT=$(npx ts-node ./read.ts)
        echo "$OUTPUT"
        awk -v content="$OUTPUT" 'BEGIN {p=1} /<!-- output-start -->/ {print; p=0} p; /<!-- output-end -->/ {print "```json\n" content "\n```\n <!-- output-end -->"; p=1}' README.md > README.tmp && mv README.tmp README.md    
      
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email github-actions@github.com
        git add README.md
        git commit -m 'Update README with latest JSON output'
        git push