name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run command and update README
      run: |
        OUTPUT=$(npx hiaguedes)
        echo "$OUTPUT"
        sed -i "/<!-- output-start -->/,/<!-- output-end -->/c\<!-- output-start -->\n$OUTPUT\n<!-- output-end -->" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email github-actions@github.com
        git add README.md
        git commit -m 'Update README with latest JSON output'
        git push